# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-18 16:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='\u5361\u53f7')),
                ('balance', models.FloatField(default=0, verbose_name='\u4f59\u989d')),
            ],
            options={
                'verbose_name': '\u94f6\u884c\u5361',
                'verbose_name_plural': '\u94f6\u884c\u5361',
            },
        ),
        migrations.CreateModel(
            name='TradeInfo',
            fields=[
                ('trade_id', models.CharField(default='', max_length=9, primary_key=True, serialize=False, verbose_name='\u4ea4\u6613\u6d41\u6c34\u53f7')),
                ('trade_type', models.CharField(choices=[('transfer', '\u8f6c\u8d26'), ('draw', '\u53d6\u6b3e'), ('deposit', '\u5b58\u6b3e')], max_length=8, verbose_name='\u4ea4\u6613\u7c7b\u578b')),
                ('trade_amount', models.FloatField(default=0, verbose_name='\u4ea4\u6613\u91d1\u989d')),
                ('trade_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4ea4\u6613\u65f6\u95f4')),
                ('trade_status', models.CharField(choices=[('success', '\u6210\u529f'), ('fail', '\u5931\u8d25')], max_length=7, verbose_name='\u4ea4\u6613\u72b6\u6001')),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_card', to='users.Card', verbose_name='\u8f6c\u51fa\u8d26\u6237')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_card', to='users.Card', verbose_name='\u8f6c\u5165\u8d26\u6237')),
            ],
            options={
                'verbose_name': '\u4ea4\u6613\u8bb0\u5f55',
                'verbose_name_plural': '\u4ea4\u6613\u8bb0\u5f55',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_card',
            field=models.CharField(default='', max_length=18, verbose_name='\u8eab\u4efd\u8bc1'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6301\u5361\u4eba'),
        ),
    ]
