# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-18 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180418_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='\u6301\u5361\u4eba'),
        ),
    ]
