# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180419_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u5361\u53f7'),
        ),
    ]
