# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180419_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeinfo',
            name='from_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_card', to='users.Card', verbose_name='\u8f6c\u51fa\u8d26\u6237'),
        ),
        migrations.AlterField(
            model_name='tradeinfo',
            name='to_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_card', to='users.Card', verbose_name='\u8f6c\u5165\u8d26\u6237'),
        ),
    ]
