# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180421_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='\u94f6\u884c\u5361\u72b6\u6001'),
        ),
    ]
