# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-27 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_card_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeinfo',
            name='from_card',
        ),
        migrations.RemoveField(
            model_name='tradeinfo',
            name='to_card',
        ),
        migrations.RemoveField(
            model_name='tradeinfo',
            name='trade_status',
        ),
        migrations.AddField(
            model_name='tradeinfo',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='\u8f6c\u51fa\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='tradeinfo',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='\u8f6c\u5165\u7528\u6237'),
        ),
    ]
