# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-27 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180427_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeinfo',
            name='trade_type',
            field=models.CharField(max_length=8, verbose_name='\u4ea4\u6613\u7c7b\u578b'),
        ),
    ]
