# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-27 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180427_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinfo',
            name='message',
            field=models.CharField(default='', max_length=500, verbose_name='\u6d88\u606f\u5185\u5bb9'),
        ),
    ]
